# Site settings
title: Biljith Thadichi
twitter_username: billyjayan
name: Biljith Thadichi

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/biljith
 - title: LinkedIn
   url: https://www.linkedin.com/in/biljith-thadichi-69859b61/
 - title: Medium
   url: https://medium.com/@biljithjayan

#Any buzzword skills you want to include
skills:
 - C++
 - Java
 - Python
 - Privacy and Security
 - Competitive Programming
 - Machine learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Lead Engineer
   start: 2019
   end: 2019
   employer: Samsung Research
   description: Worked on Smart Anti Tracking Research and Dev team. This team developed and shipped Smart Anti Tracking - A feature to prevent online trackers from stealing user's privacy.
 - title: Senior Software Engineer
   start: 2017
   end: 2018
   employer: Samsung Research
   description: Part of the Loader and Network module of Samsung Internet Browser. Responsibilites included HTTP cache, Network errors, HTTP Authentication, Proxy support and Protected Browsing. Developed Protected Browsing feature that prevents users from visiting malicious URLs.
 - title: Software Engineer
   start: 2016
   end: 2017
   employer: Samsung Research
   description: Developed 'Smart Knob' - a project that involved using BLE, an Android app and an Atmega microcontroller to configure the button for various tasks.
 - title: Student Trainee
   start: 2015
   end: 2015
   employer: Samsung Research
   description: Developed an Android app to measure the battery, CPU and other critical resources used by other apps.

#Education is required
education:
 - level: Bachelor of Tech (B.Tech.)
   date: 2016
   subject: Computer Engineering
   school: Veermata Jijabai Technological Institute

#This section is optional (as is the image link below)
# coursera:
#    profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#    courses:
#     - title: Functional Programming Principles in Scala
#       link: https://www.coursera.org/course/progfun
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#       date: September 16, 2013
#     - title: Algorithms Design and Analysis, Part 1
#       link: https://www.coursera.org/specializations/algorithms
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#       date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    profileurl: https://speakerdeck.com/robhinds
#    talks:
#     - title: Product Management for Engineers
#       speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#       conference: API Conference, Berlin 2018
#     - title: Agile Machine Learning - from Theory to Production
#       speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#       conference: W-JAX Conference, Munich 2017 (London 2017)

# List of interesting Github repo/projects to include - optional
github:
 - biljith/Tetris
 - biljith/leetcode

#Stackoverflow flair is optional
# stackoverflow:
#    profileurl: http://stackoverflow.com/users/258813/rhinds
#    flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
    Studying Masters in Computer Science at the University of Colorado at Boulder. One of my major interests is in Privacy and Security of users as they browse online.
    That and a general love for everything Computer Science.
    Previously worked as a part of the loader and network team for Samsung Internet, a Chromium based browser for mobile devices.
    Interested in open source, designing data structures and algorithms, problem solving, design patterns and applying good coding practices to make the world a better place, one line of code at a time.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
     <strong>Smart Anti Tracking</strong>: One of my biggest research projects happened when I was working for Samsung's browser team. You know how ad providers online seem to know a little too much about you? We wanted the users of our browsers to have their privacy in their control.
     This project involved everything from data collection, feature engineering, handling class imbalance and training to give me a good idea of how an ML project's lifecycle is. This feature is a part of Samsung Internet Browser if you would like to give it a try - <a target='_blank' href='https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser'>Samsung Internet</a>
     <br><strong>Article Detection on Webpages</strong>: Almost all major browsers on Android have Reader mode -  a mode in which the browser removes extraneous content apart from the main article and presents it to the user. The challenge is in identifying which pages have articles in them.
     This project applied everything I learned in Smart Anti Tracking and we came up with a model that classifies Webpages.
#    <strong>Java</strong>: I am experienced in a variety of Java APIâ€™s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
#    <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
#    <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
#    <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
#    <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
#    I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
#    As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
#    I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
